# Generated by Django 5.1.1 on 2024-09-14 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chais/')),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('EL', 'ELAICHI')], max_length=2)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
